### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ashenafykebede** [ashenafykebede/movies#1]
- [x] [repo](https://github.com/ashenafykebede/movies)
- [x] [many small, well-named commits per component](https://github.com/ashenafykebede/movies/commits/)
- [x] a nice README
- [pull requests](https://github.com/ashenafykebede/movies/pulls)
  - [x] code review checklist is complete (write your own check list!)
  - [ ] the reviewer merged the code
